### ISSUE TITLE
Demo link

### ISSUE THREAD

**Issue by josephernest** [florianguenther/zui53#14]
Hi @florianguenther, the demo link is no more available. Do you think you could put an online demo (e.g. github.io)? 

I'd like to test / use your library (I'm currently trying to add mobile / touch devices capabilities for https://github.com/josephernest/bigpicture.js/).

**Comment by florianguenther** [comment]
Sorry, but this library is no longer maintained

**Comment by josephernest** [comment]
@florianguenther Even if no longer updated, it would be cool to have an online demo of the current state, the project really looks great! Thanks in advance :)

**Comment by florianguenther** [comment]
please check the "demos" folder

**Comment by josephernest** [comment]
I already did @florianguenther but it didn't seem to be working on my browser when I opened them. Could you just put them online (e.g. in the standard github.io / github-pages)?

**Comment by florianguenther** [comment]
Why do you believe it will work if I put it online? Maybe your browser is not supported. Please understand that I cannot put any effort in this project.
